[package]
name = "timsextractor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
timsrust = "0.2.2"
rusqlite = { version = "0.29.0", features = ["bundled"] }

# Serialization
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
apache-avro = "0.16.0"
rayon = "1.8.0"
indicatif = {version = "*", features = ["rayon"]}

# for viz feature
rerun = "0.11.0"
rand = "0.8.5"

log = "0.4"
pretty_env_logger = "0.4"

[features]
viz = []
f64 = []

# [profile.release]
# debug = true
