
fn_params_layout = "Vertical"
match_block_trailing_comma = true
newline_style = "Unix"

## Unstable features :(
# group_imports = "StdExternalCrate"
# imports_granularity = "Module"
# imports_layout = "Vertical"
# merge_imports = true
# format_strings = true
# struct_lit_single_line = false
